name: simontravelsbeyond
favicon: null
layout_spectrum: 0.9622587461490184
typography_spectrum: 0.25149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.23591165454126894
  saturation: 0.7281908683944494
  rhythmicContrast: 0.09767104685306549
purpose: []
